import os

LINKEDIN_USERNAME = os.getenv("LINKEDIN_USERNAME") or os.getenv("LINKEDIN_EMAIL")
LINKEDIN_PASSWORD = os.getenv("LINKEDIN_PASSWORD")

MAX_ACCEPT_PER_RUN = 15
MIN_DELAY_SEC = 3
MAX_DELAY_SEC = 7
